import { describe, expect, it } from 'vitest';

import {
  renderLaunchdPlist,
  renderNohupWrapper,
  renderSystemdUnit,
} from '../commands/service.js';

const paths = {
  projectRoot: '/opt/nanotars',
  home: '/home/alice',
  nodePath: '/usr/bin/node',
};

describe('service command renderers', () => {
  it('renders systemd unit through the TS daemon entrypoint', () => {
    const unit = renderSystemdUnit(paths);
    expect(unit).toContain('ExecStart=/usr/bin/node /opt/nanotars/dist/cli/nanotars.js daemon');
    expect(unit).toContain('EnvironmentFile=-/opt/nanotars/.env');
    expect(unit).toContain('StandardOutput=append:/opt/nanotars/logs/nanotars.log');
  });

  it('renders launchd plist through the TS daemon entrypoint', () => {
    const plist = renderLaunchdPlist(paths);
    expect(plist).toContain('<string>/usr/bin/node</string>');
    expect(plist).toContain('<string>/opt/nanotars/dist/cli/nanotars.js</string>');
    expect(plist).toContain('<string>daemon</string>');
    expect(plist).toContain('<string>/opt/nanotars/logs/nanotars.error.log</string>');
  });

  it('renders nohup wrapper through the TS daemon entrypoint', () => {
    const wrapper = renderNohupWrapper(paths);
    expect(wrapper).toContain('Generated by: nanotars service install');
    expect(wrapper).toContain('"/usr/bin/node" "/opt/nanotars/dist/cli/nanotars.js" daemon');
    expect(wrapper).toContain('"/opt/nanotars/nanotars.pid"');
  });
});
