#!/usr/bin/env bash
# nanotars — single-command wrapper for the install at __INSTALL_DIR__.
# Generated by setup.sh. Safe to regenerate (re-run setup.sh).
#
# Usage:
#   nanotars                     # open Claude Code in the install dir
#   nanotars start | stop |      # service control
#   nanotars restart | status |
#   nanotars logs
#   nanotars pair-main           # issue a pairing code for the main chat
#   nanotars auth <channel>      # run channel auth (e.g. nanotars auth whatsapp)
#   nanotars setup               # re-run setup.sh
#   nanotars <prompt...>         # claude "<prompt...>" (one-shot pass-through)

set -euo pipefail

NANOTARS_INSTALL_DIR="__INSTALL_DIR__"

if [ ! -d "$NANOTARS_INSTALL_DIR" ]; then
  echo "nanotars: install dir $NANOTARS_INSTALL_DIR not found. Re-run setup.sh." >&2
  exit 1
fi

cd "$NANOTARS_INSTALL_DIR"

case "${1:-}" in
  "")
    exec claude
    ;;
  start|stop|restart|status|logs|pair-main|auth)
    exec bash ./nanotars.sh "$@"
    ;;
  setup)
    shift
    exec bash ./setup.sh "$@"
    ;;
  -h|--help|help)
    sed -n '2,13p' "$0" | sed 's/^# \?//'
    ;;
  *)
    exec claude "$@"
    ;;
esac
